version: "3.8"

services:
  web:
    build: .
    command: gunicorn fininstitution.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - pgdb
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web
  pgdb:
    image: postgres:12.0-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:
